### ISSUE TITLE
when I run the code this error apeared

### ISSUE THREAD

**Issue by MohammadEftekhar** [exowanderer/arctor#1]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-c825e7188d70> in <module>
     12 # from tqdm import tqdm_notebook as tqdm
     13 
---> 14 from arctor import create_raw_lc_stddev, Arctor, run_multiple_pymc3#, setup_and_plot_GTC
     15 from arctor.utils import setup_and_plot_GTC, compute_delta_sdnr
     16 # from arctor.utils import fit_2D_time_vs_other

~/.local/lib/python3.8/site-packages/arctor/__init__.py in <module>
      1 from . import *
----> 2 from .arctor import Arctor
      3 from .utils import *
      4 from .dwt import *
      5 

~/.local/lib/python3.8/site-packages/arctor/arctor.py in <module>
     23 from tqdm import tqdm
     24 
---> 25 from .utils import (
     26     center_one_trace,
     27     fit_one_slopes,

~/.local/lib/python3.8/site-packages/arctor/utils.py in <module>
   1006                        do_mcmc=False, save_as_you_go=False,
   1007                        injected_light_curve=1.0, working_dir='./',
-> 1008                        base_name=f'{planet_name}_fine_grain_photometry_208ppm'):
   1009 
   1010     decor_set = [xcenters, ycenters, trace_angles, trace_lengths]

NameError: name 'planet_name' is not defined

**Comment by exowanderer** [comment]
Hello @MohammadEftekhar, I just got around to seeing this issue. Thank you for posting it.

You have to define `planet_name = <name of directory>` or `base_name = <filename for saving>`

In response to your issue post, I set a default `planet_name="planet_name"` to make up for that though.

Thank you for your work

**Comment by exowanderer** [comment]
I also changed the master branch name to "main"
